[
  {
    id: '7cbaebe3-51af-438c-b997-937330eed8d8',
    authorId: '4943cb73-9db3-4055-b5d8-67ecd96a43ef',
    createdAt: '2025-12-20T10:48:36.407Z',
    eventEndDate: null,
    eventStartDate: '2026-02-01T17:00:00.000Z',
    title: 'Party2',
    updatedAt: '2026-01-31T17:34:51.300Z',
    isToBeInNewsSection: true,
    isToBePublished: true,
    isToBeInRssChannel: false,
    newsSectionImageUrl: '2025_12_20__news___94y65cbq1r4rdwbj36opxq.jpg',
    shortDescription: 'rfewrfer',
    detailedDescription:
      '<p>tryhrtyhrtyhyt</p><p></p><p>Can we use React Server Actions (now known as Server Functions) for data fetching? That&#39;s a very good question that <a href="https://www.reddit.com/r/nextjs/comments/188dcfz/fetching_data_in_server_actions/" rel="noopener noreferrer" target="_blank">pops up</a> from <a href="https://github.com/vercel/next.js/discussions/58674" rel="noopener noreferrer" target="_blank">time</a> to <a href="https://www.robinwieruch.de/next-server-actions-fetch-data/" rel="noopener noreferrer" target="_blank">time</a>. But is it really a good idea to <em>fetch</em> data with Server Actions? &quot;Actions&quot; kinda imply that they are not for fetching. Why would anyone even consider it?</p><p>Let&#39;s find out! We&#39;ll start by understanding what they are in the first place, move to the pros and cons, and finish with a definitive answer to that question. For real this time, not the usual &quot;it depends&quot;, I promise!</p><p>Oh, and just in case: we&#39;re talking only about <strong>fetching on the client</strong> here. For Server Components, you don&#39;t need Actions to fetch data. You can just import functions directly right away.</p><p>The repo with examples to follow along is <a href="https://github.com/developerway/react-actions-data-fetching" rel="noopener noreferrer" target="_blank">here</a>.</p><p></p><p></p><h2>What Are React Actions (Server Functions)</h2><h2></h2><p>Let&#39;s start with what those Actions are, to make sure we&#39;re on the same page.</p><p>Server Functions (<a href="https://react.dev/reference/rsc/server-functions" rel="noopener noreferrer" target="_blank">renamed from Server Actions in 2024</a>) are a relatively new React feature that allows developers to call backend code from frontend components. Not via boring GET/POST requests, but directly, as a function that you import.</p><p>It would typically be something like this. Fi the top, and every available action is just an export from this file. Everything inside is server code.</p><p>Then, insidecan trigger things on the server directly.</p><p>Whether it&#39;s a good idea to write your backend with React like that or not is a completely different and potentially heated discussion. For today, let&#39;s focus on how this magic works.</p><p>If you haven&#39;t downloaded the repo with the examples yet, <a href="https://github.com/developerway/react-actions-data-fetching" rel="noopener noreferrer" target="_blank">now would be the time</a>. You need <code>src/app/simple-action-example</code> folder. Start the code in dev mode, open the <code>/simple-action-example</code> URL, and you&#39;ll see exactly the same button.</p><p>Open Chrome&#39;s Console and click the button Only the &quot;client&quot; log shows up here. Open the terminal window with the server logs, and you should see this:</p><p></p><p></p><p>The &quot;server&quot; part is here. This is kinda cool. The code feels clean, and most importantly, we have total type safety here, with all its benefits like confidence in data and autocomplete in your IDE.</p><p>Along with our &quot;server There is no magic, yet again.</p><p>Our Actions are nothing more than POST requests. If you click any of them, you&#39;ll see your exact payload that we send as an argument to the <code>saveSomething</code> function.</p><p></p><p>The &quot;server&quot; part is here. This is kinda cool. The code feels clean, and most importantly, we have total type safety here, with all its benefits like confidence in data and autocomplete in your IDE.</p><p>Along with our &quot;server There is no magic, yet again.</p><p>Our Actions are nothing more than POST requests. If you click any of them, you&#39;ll see your exact payload that we send as an argument to the <code>saveSomething</code> function.</p><p></p><p></p><p></p><p>The &quot;server&quot; part is here. This is kinda cool. The code feels clean, and most importantly, we have total type safety here, with all its benefits like confidence in data and autocomplete in your IDE.</p><p>Along with our &quot;server There is no magic, yet again.</p><p>Our Actions are nothing more than POST requests. If you click any of them, you&#39;ll see your exact payload that we send as an argument to the <code>saveSomething</code> function.</p><p></p><p></p><p></p>',
    isPayed: false,
    newsSectionImageAlt: 'efwer',
    visibleFrom: '2025-12-20T00:00:00.048Z',
    visibleTo: '2026-02-01T17:00:00.000Z',
    kindOfEnterInfo: 'rtyhetyh',
    eventForWhom: ['CHILDREN'],
    places: ['ART_ROOM', 'DANCING_ROOM'],
    isToBeOnlyInNewsSection_NotSeenInEvents: false,
    isDateToBeHiddenInNewsSection: false,
    isToBeInSlider: true,
    sliderImageAlt: 'etyhty',
    sliderImageUrl: '2025_12_20__event___50g0orntagwgr54qxcr8p6.jpg',
    visibleInSliderFrom: '2025-12-20T00:00:00.048Z',
    eventTypes: ['OTHERS', 'LECTURE'],
    customLinkToDetails: null,
    isCustomLinkToDetails: false,
    visibleInSliderTo: '2026-01-04T17:00:00.000Z',
    ticketBuyingId: null,
    images: [
      {
        id: 'f7c1ad00-85c9-479f-8215-b6e02722ce70',
        url: '2025_12_20__event___t2swgmno2o9zi3xi3ogckk.jpg',
        alt: 'etyhty',
        additionInfoThatMustBeDisplayed: null,
        eventId: '7cbaebe3-51af-438c-b997-937330eed8d8',
        index: 0,
      },
    ],
  },
];
