'use client';

import { useLayoutState } from '@/globalState/layoutState';
import clsx from 'clsx';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  ////logic
  const currentMode = useLayoutState().getLayoutMode();
  const currentFontSize = useLayoutState().getFontSize();

  ////tsx
  return (
    <html lang="en">
      <body
        className={clsx(
          'bg-skin-fill',
          currentMode === 'NORMAL' ? null : 'theme-contrast',
          currentFontSize === 'NORMAL'
            ? null
            : currentFontSize === 'BIGGER'
            ? 'theme-font-size-bigger'
            : 'theme-font-size-biggest'
        )}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
